### ISSUE TITLE
Provide optional support for using s3 buckets to store the lambdas

### ISSUE THREAD

**Issue by segfault** [covidgreen/covid-green-infra#12]
Our deployment workflow attempts to force all environment changes through Terraform in order to utilize that as a single source of truth for deployments to our environments. To support that we will need to be able to provide specific references to all the deployable resources. This is already possible for the containers deployed in ECS, and to complete the workflow we need to add similar behavior to the lambdas.

Out of scope is the management of the bucket where the lambdas will live. The focus is entirely on allowing for the lambdas to refer to specific s3 keys in an s3 bucket. The s3 bucket itself is expected to be shared by all lambdas.

The default behavior involving the deployment of stub lambdas should be retained.

This should result in `tfvars` like:
```
lambda_bucket = "s3://my_s3_artifacts"
lambda_exposures_s3_key = "common_lambdas/v1.0.1.zip"
lambda_stats_s3_key = "region_lambdas/v1.0.2.zip"
```

**Comment by segfault** [comment]
pulling in @pmcgrath @dgonzalez to discuss before a PR

**Comment by pmcgrath** [comment]
@segfault Where is the policy that is going to grant access to the S3 bucket going to live and be managed ? 
That is the part that allows lambda to use the `lambda_bucket` and `lambda_exposures_s3_key` as the source file

**Comment by segfault** [comment]
In our case we have the bucket managed by another set of Terraform that handles our development and deployment infrastructure.

**Comment by pmcgrath** [comment]
@segfault  Yep I get that, but did you need to do anything to allow the lambda roles to be able to access the S3 bucket ?

**Comment by segfault** [comment]
In the environments we have we didn't need to do anything to the covid-green-infra side to allow the read. The current policy of `Allow: s3:*` covers us since the bucket is in the same account.

**Comment by pmcgrath** [comment]
This has been implemented in this commit https://github.com/covidgreen/covid-green-infra/commit/7dd0e1f37b15c75a899db057622a49f8ca9e0dda
