### ISSUE TITLE
Nominating David Gonzalez (dgonzalez) and Mark Guzman (segfault) as members

### ISSUE THREAD

**Issue by jasnell** [covidgreen/covid-green-infra#5]
@covidgreen/members ... I'd like to nominate @dgonzalez and @segfault as contributors. @dgonzalez is at NearForm and works on the infrastructure pieces of the application. @segfault is from the Bloomberg team. Please 👍🏻 for either or both. If there are no objections I will add both to the @covidgreen/members team by Friday

**Comment by ShaunBaker** [comment]
👍

**Comment by jackdclark** [comment]
👍

**Comment by jasnell** [comment]
@dgonzalez and @segfault ... considering this accepted! Can you please open PRs adding yourselves to the list of contributors in the various repo READMEs. I'll add you to the @covidgreen/members team now

**Comment by dgonzalez** [comment]
@jasnell I cannot merge commits... looks like I am not in the required team (@covidgreen/members). Would you mind?

**Comment by jasnell** [comment]
@dgonzalez ... you should have received an invite.

![image](https://user-images.githubusercontent.com/439929/89909555-0d26fd80-dba4-11ea-8f36-6335c53da972.png)
